# Generated by Django 2.1.7 on 2019-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codementorwebhook',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
