# Generated by Django 2.1.7 on 2019-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0003_codementorwebhook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codementor_web_secret',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codementor_api_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
