# Generated by Django 4.0.2 on 2022-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0005_auto_20190820_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codementorwebhook',
            name='data',
            field=models.JSONField(),
        ),
    ]
