# Generated by Django 4.0.2 on 2022-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0006_alter_codementorwebhook_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='codementorwebhook',
            name='google_event_id',
            field=models.CharField(blank=True, default=None, max_length=26, null=True),
        ),
    ]
