# Generated by Django 4.0.2 on 2022-03-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0007_codementorwebhook_google_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=10, unique=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('session_length', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('declined', 'declined'), ('rescheduled', 'rescheduled')], default='created', max_length=11)),
                ('google_event_id', models.CharField(blank=True, max_length=26, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codementor.client')),
            ],
        ),
    ]
