# Generated by Django 4.0.2 on 2022-03-01 21:57

import datetime
import pytz
from django.db import migrations


def create_sessions(apps, schema_editor):
    CONFIRMED = 'confirmed'
    CodementorWebhook = apps.get_model('codementor', 'CodementorWebhook')
    Client = apps.get_model('codementor', 'Client')
    Session = apps.get_model('codementor', 'Session')
    for record in CodementorWebhook.objects.all():
        client_info = record.data['mentee']
        client, created = Client.objects.get_or_create(**client_info)
        scheduled_start = datetime.datetime.fromtimestamp(
            record.data['appointment_timestamp'], tz=pytz.UTC)
        Session.objects.get_or_create(session_id=record.data['id'], defaults={
            'client': client, 'status': CONFIRMED, 'google_event_id': record.google_event_id,
            'scheduled_start': scheduled_start})


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0008_client_session'),
    ]

    operations = [
        migrations.RunPython(create_sessions, migrations.RunPython.noop),
    ]
