# Generated by Django 4.0.2 on 2022-03-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0010_auto_20220301_2157_populate_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='codementorwebhook',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codementor.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='amount_before_platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
