# Generated by Django 4.0.2 on 2022-03-01 23:02

from django.db import migrations


def populate_webhook_session(apps, schema_editor):
    CodementorWebhook = apps.get_model('codementor', 'CodementorWebhook')
    Session = apps.get_model('codementor', 'Session')

    for record in CodementorWebhook.objects.all():
        session = Session.objects.filter(session_id=record.data['id']).first()
        if not session:
            print(f"No session for Webhook {record.data['id']}")
            continue
        if not record.google_event_id:
            continue
        session.google_event_id = record.google_event_id
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('codementor', '0011_codementorwebhook_session_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_webhook_session, migrations.RunPython.noop),
    ]
